var RentConstants = {

  ENTRY_CLICKED: "ENTRY_CLICKED",
  FETCH_ENTRIES: "FETCH_ENTRIES",
  NEW_BOOKING: "NEW_BOOKING",
  FILTER_CHANGE: "FILTER_CHANGE",
  REVIEW_SUBMITTED: "REVIEW_SUBMITTED",
  FETCH_REVIEWS: "FETCH_REVIEWS",
  NEW_REVIEW: "NEW_REVIEW"

}
